import { HeroStats, HeroArchetype, AbilityType, BuffType } from '../types';
import { COLORS, MELEE_RANGE } from '../constants';

export const heroDataMap: Record<string, HeroStats> = {
  iron_guard: {
    id: 'iron_guard',
    name: 'Iron Guard',
    label: 'IG',
    archetype: HeroArchetype.TANK,
    color: COLORS.IRON_GUARD,
    maxHP: 1200,
    maxMana: 300,
    damage: 35,
    armor: 12,
    attackRange: MELEE_RANGE,
    moveSpeed: 180,
    abilities: [
      {
        id: 'ig_q', name: 'Shield Bash', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 40, cooldown: 5,
        damage: 60, range: 120, projectileSpeed: 600, radius: 15,
        buffType: BuffType.STUN, buffDuration: 0.8,
        description: 'Short-range bash that stuns',
      },
      {
        id: 'ig_w', name: 'Iron Fortress', slot: 'W',
        type: AbilityType.SELF_BUFF,
        manaCost: 50, cooldown: 10,
        buffType: BuffType.SHIELD, buffValue: 200, buffDuration: 4,
        description: 'Gains a 200HP shield for 4s',
      },
      {
        id: 'ig_e', name: 'Earthquake', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 100, cooldown: 30,
        damage: 120, radius: 150, duration: 1.5,
        buffType: BuffType.SLOW, buffValue: 0.5, buffDuration: 2,
        description: 'AoE slam that damages and slows enemies',
      },
    ],
  },

  shadow_blade: {
    id: 'shadow_blade',
    name: 'Shadow Blade',
    label: 'SB',
    archetype: HeroArchetype.ASSASSIN,
    color: COLORS.SHADOW_BLADE,
    maxHP: 600,
    maxMana: 250,
    damage: 55,
    armor: 4,
    attackRange: MELEE_RANGE,
    moveSpeed: 260,
    abilities: [
      {
        id: 'sb_q', name: 'Shadow Strike', slot: 'Q',
        type: AbilityType.DASH,
        manaCost: 35, cooldown: 5,
        damage: 80, dashDistance: 200, dashSpeed: 800,
        description: 'Dash forward dealing damage to first enemy',
      },
      {
        id: 'sb_w', name: 'Poison Blade', slot: 'W',
        type: AbilityType.SELF_BUFF,
        manaCost: 40, cooldown: 8,
        buffType: BuffType.STAT_BUFF, buffValue: 30, buffDuration: 5,
        description: 'Next attacks deal +30 damage for 5s',
      },
      {
        id: 'sb_e', name: 'Death Mark', slot: 'E',
        type: AbilityType.DASH,
        manaCost: 80, cooldown: 28,
        damage: 180, dashDistance: 300, dashSpeed: 1000,
        buffType: BuffType.SILENCE, buffDuration: 1.5,
        description: 'Long dash dealing massive damage and silencing',
      },
    ],
  },

  flame_witch: {
    id: 'flame_witch',
    name: 'Flame Witch',
    label: 'FW',
    archetype: HeroArchetype.MAGE,
    color: COLORS.FLAME_WITCH,
    maxHP: 550,
    maxMana: 400,
    damage: 30,
    armor: 3,
    attackRange: 300,
    moveSpeed: 200,
    abilities: [
      {
        id: 'fw_q', name: 'Fireball', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 35, cooldown: 4,
        damage: 90, range: 400, projectileSpeed: 450, radius: 8,
        description: 'Launches a fireball',
      },
      {
        id: 'fw_w', name: 'Flame Ring', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 60, cooldown: 10,
        damage: 40, radius: 100, duration: 3,
        buffType: BuffType.DOT, buffValue: 15, buffDuration: 3,
        description: 'Creates a ring of fire that burns enemies',
      },
      {
        id: 'fw_e', name: 'Meteor Storm', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 120, cooldown: 32,
        damage: 200, radius: 130, duration: 2,
        buffType: BuffType.STUN, buffDuration: 1,
        description: 'Massive AoE damage with stun',
      },
    ],
  },

  frost_archer: {
    id: 'frost_archer',
    name: 'Frost Archer',
    label: 'FA',
    archetype: HeroArchetype.CARRY,
    color: COLORS.FROST_ARCHER,
    maxHP: 580,
    maxMana: 300,
    damage: 50,
    armor: 4,
    attackRange: 350,
    moveSpeed: 220,
    abilities: [
      {
        id: 'fa_q', name: 'Frost Arrow', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 30, cooldown: 4,
        damage: 70, range: 450, projectileSpeed: 500, radius: 6,
        buffType: BuffType.SLOW, buffValue: 0.4, buffDuration: 2,
        description: 'Arrow that slows target',
      },
      {
        id: 'fa_w', name: 'Ice Trap', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 50, cooldown: 12,
        damage: 30, radius: 80, duration: 3,
        buffType: BuffType.ROOT, buffDuration: 1.5,
        description: 'Creates ice zone that roots enemies',
      },
      {
        id: 'fa_e', name: 'Blizzard', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 100, cooldown: 30,
        damage: 150, radius: 160, duration: 3,
        buffType: BuffType.SLOW, buffValue: 0.6, buffDuration: 3,
        description: 'Large blizzard that damages and slows',
      },
    ],
  },

  holy_priest: {
    id: 'holy_priest',
    name: 'Holy Priest',
    label: 'HP',
    archetype: HeroArchetype.SUPPORT,
    color: COLORS.HOLY_PRIEST,
    maxHP: 650,
    maxMana: 450,
    damage: 25,
    armor: 5,
    attackRange: 280,
    moveSpeed: 210,
    abilities: [
      {
        id: 'hp_q', name: 'Holy Bolt', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 30, cooldown: 4,
        damage: 60, range: 350, projectileSpeed: 400, radius: 7,
        description: 'Deals damage to enemy or heals ally',
        healAmount: 80,
      },
      {
        id: 'hp_w', name: 'Healing Circle', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 70, cooldown: 12,
        radius: 120, duration: 4,
        healAmount: 30,
        description: 'Area heal over time for allies',
      },
      {
        id: 'hp_e', name: 'Divine Shield', slot: 'E',
        type: AbilityType.BUFF,
        manaCost: 100, cooldown: 35,
        range: 300,
        buffType: BuffType.SHIELD, buffValue: 300, buffDuration: 5,
        description: 'Grants massive shield to target ally',
      },
    ],
  },

  storm_caller: {
    id: 'storm_caller',
    name: 'Storm Caller',
    label: 'SC',
    archetype: HeroArchetype.MAGE,
    color: COLORS.STORM_CALLER,
    maxHP: 520,
    maxMana: 420,
    damage: 28,
    armor: 3,
    attackRange: 320,
    moveSpeed: 210,
    abilities: [
      {
        id: 'sc_q', name: 'Lightning Bolt', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 35, cooldown: 4,
        damage: 85, range: 400, projectileSpeed: 600, radius: 6,
        description: 'Fast lightning bolt',
      },
      {
        id: 'sc_w', name: 'Chain Lightning', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 60, cooldown: 9,
        damage: 60, radius: 150, duration: 0.5,
        description: 'Instant AoE lightning burst',
      },
      {
        id: 'sc_e', name: 'Thunderstorm', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 110, cooldown: 30,
        damage: 180, radius: 180, duration: 2.5,
        buffType: BuffType.STUN, buffDuration: 0.8,
        description: 'Large thunderstorm with stun',
      },
    ],
  },

  blade_dancer: {
    id: 'blade_dancer',
    name: 'Blade Dancer',
    label: 'BD',
    archetype: HeroArchetype.CARRY,
    color: COLORS.BLADE_DANCER,
    maxHP: 620,
    maxMana: 280,
    damage: 48,
    armor: 5,
    attackRange: MELEE_RANGE,
    moveSpeed: 240,
    abilities: [
      {
        id: 'bd_q', name: 'Spinning Slash', slot: 'Q',
        type: AbilityType.AREA,
        manaCost: 30, cooldown: 5,
        damage: 70, radius: 90, duration: 0.3,
        description: 'Spin attack hitting nearby enemies',
      },
      {
        id: 'bd_w', name: 'Blade Fury', slot: 'W',
        type: AbilityType.SELF_BUFF,
        manaCost: 50, cooldown: 10,
        buffType: BuffType.STAT_BUFF, buffValue: 25, buffDuration: 6,
        description: 'Attack damage boost for 6s',
      },
      {
        id: 'bd_e', name: 'Omnislash', slot: 'E',
        type: AbilityType.DASH,
        manaCost: 90, cooldown: 28,
        damage: 200, dashDistance: 250, dashSpeed: 900,
        description: 'Dash through enemies dealing massive damage',
      },
    ],
  },

  war_drummer: {
    id: 'war_drummer',
    name: 'War Drummer',
    label: 'WD',
    archetype: HeroArchetype.SUPPORT,
    color: COLORS.WAR_DRUMMER,
    maxHP: 700,
    maxMana: 380,
    damage: 30,
    armor: 7,
    attackRange: MELEE_RANGE,
    moveSpeed: 220,
    abilities: [
      {
        id: 'wd_q', name: 'War Cry', slot: 'Q',
        type: AbilityType.AREA,
        manaCost: 35, cooldown: 7,
        radius: 150, duration: 0.3,
        healAmount: 50,
        description: 'Heals all nearby allies',
      },
      {
        id: 'wd_w', name: 'Battle Drums', slot: 'W',
        type: AbilityType.BUFF,
        manaCost: 55, cooldown: 12,
        range: 200,
        buffType: BuffType.STAT_BUFF, buffValue: 20, buffDuration: 8,
        description: 'Buffs nearby allies damage',
      },
      {
        id: 'wd_e', name: 'Rallying Roar', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 90, cooldown: 30,
        radius: 200, duration: 1,
        healAmount: 120,
        buffType: BuffType.SHIELD, buffValue: 150, buffDuration: 5,
        description: 'Massive heal + shield to all nearby allies',
      },
    ],
  },

  venom_stalker: {
    id: 'venom_stalker',
    name: 'Venom Stalker',
    label: 'VS',
    archetype: HeroArchetype.ASSASSIN,
    color: COLORS.VENOM_STALKER,
    maxHP: 560,
    maxMana: 270,
    damage: 42,
    armor: 4,
    attackRange: 250,
    moveSpeed: 240,
    abilities: [
      {
        id: 'vs_q', name: 'Venom Spit', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 30, cooldown: 4,
        damage: 50, range: 350, projectileSpeed: 450, radius: 7,
        buffType: BuffType.DOT, buffValue: 20, buffDuration: 3,
        description: 'Poison projectile with DoT',
      },
      {
        id: 'vs_w', name: 'Toxic Cloud', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 50, cooldown: 10,
        damage: 30, radius: 100, duration: 4,
        buffType: BuffType.SLOW, buffValue: 0.3, buffDuration: 2,
        description: 'Poison cloud that slows and damages',
      },
      {
        id: 'vs_e', name: 'Plague Strike', slot: 'E',
        type: AbilityType.DASH,
        manaCost: 80, cooldown: 25,
        damage: 140, dashDistance: 250, dashSpeed: 850,
        buffType: BuffType.DOT, buffValue: 30, buffDuration: 5,
        description: 'Dash that applies heavy poison',
      },
    ],
  },

  stone_golem: {
    id: 'stone_golem',
    name: 'Stone Golem',
    label: 'SG',
    archetype: HeroArchetype.TANK,
    color: COLORS.STONE_GOLEM,
    maxHP: 1100,
    maxMana: 280,
    damage: 40,
    armor: 15,
    attackRange: MELEE_RANGE,
    moveSpeed: 160,
    abilities: [
      {
        id: 'sg_q', name: 'Boulder Throw', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 40, cooldown: 6,
        damage: 80, range: 300, projectileSpeed: 350, radius: 12,
        buffType: BuffType.STUN, buffDuration: 1,
        description: 'Slow boulder that stuns on hit',
      },
      {
        id: 'sg_w', name: 'Stone Skin', slot: 'W',
        type: AbilityType.SELF_BUFF,
        manaCost: 50, cooldown: 12,
        buffType: BuffType.SHIELD, buffValue: 250, buffDuration: 5,
        description: 'Massive damage shield',
      },
      {
        id: 'sg_e', name: 'Avalanche', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 90, cooldown: 32,
        damage: 160, radius: 140, duration: 2,
        buffType: BuffType.STUN, buffDuration: 1.2,
        description: 'AoE rocks with long stun',
      },
    ],
  },

  lightning_duelist: {
    id: 'lightning_duelist',
    name: 'Lightning Duelist',
    label: 'LD',
    archetype: HeroArchetype.CARRY,
    color: COLORS.LIGHTNING_DUELIST,
    maxHP: 580,
    maxMana: 280,
    damage: 52,
    armor: 5,
    attackRange: MELEE_RANGE,
    moveSpeed: 250,
    abilities: [
      {
        id: 'ld_q', name: 'Shock Strike', slot: 'Q',
        type: AbilityType.DASH,
        manaCost: 30, cooldown: 4,
        damage: 65, dashDistance: 150, dashSpeed: 700,
        description: 'Quick short dash with damage',
      },
      {
        id: 'ld_w', name: 'Static Field', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 45, cooldown: 8,
        damage: 50, radius: 100, duration: 0.3,
        buffType: BuffType.SLOW, buffValue: 0.3, buffDuration: 2,
        description: 'Burst AoE that slows',
      },
      {
        id: 'ld_e', name: 'Thunder God', slot: 'E',
        type: AbilityType.SELF_BUFF,
        manaCost: 90, cooldown: 30,
        buffType: BuffType.STAT_BUFF, buffValue: 40, buffDuration: 8,
        description: 'Massive attack boost for 8s',
      },
    ],
  },

  blood_shaman: {
    id: 'blood_shaman',
    name: 'Blood Shaman',
    label: 'BS',
    archetype: HeroArchetype.MAGE,
    color: COLORS.BLOOD_SHAMAN,
    maxHP: 600,
    maxMana: 400,
    damage: 32,
    armor: 4,
    attackRange: 300,
    moveSpeed: 200,
    abilities: [
      {
        id: 'bs_q', name: 'Blood Bolt', slot: 'Q',
        type: AbilityType.PROJECTILE,
        manaCost: 35, cooldown: 5,
        damage: 75, range: 380, projectileSpeed: 420, radius: 7,
        healAmount: 30,
        description: 'Damages enemy and heals self',
      },
      {
        id: 'bs_w', name: 'Blood Pool', slot: 'W',
        type: AbilityType.AREA,
        manaCost: 55, cooldown: 10,
        damage: 50, radius: 110, duration: 3,
        buffType: BuffType.SLOW, buffValue: 0.3, buffDuration: 1.5,
        description: 'AoE damage zone with slow',
      },
      {
        id: 'bs_e', name: 'Hemomancy', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 100, cooldown: 28,
        damage: 160, radius: 140, duration: 2,
        healAmount: 100,
        description: 'AoE damage that heals allies in range',
      },
    ],
  },

  phantom_knight: {
    id: 'phantom_knight',
    name: 'Phantom Knight',
    label: 'PK',
    archetype: HeroArchetype.TANK,
    color: COLORS.PHANTOM_KNIGHT,
    maxHP: 950,
    maxMana: 320,
    damage: 38,
    armor: 10,
    attackRange: MELEE_RANGE,
    moveSpeed: 200,
    abilities: [
      {
        id: 'pk_q', name: 'Spectral Slash', slot: 'Q',
        type: AbilityType.DASH,
        manaCost: 35, cooldown: 5,
        damage: 70, dashDistance: 180, dashSpeed: 700,
        description: 'Ghost dash through enemies',
      },
      {
        id: 'pk_w', name: 'Phantom Shroud', slot: 'W',
        type: AbilityType.SELF_BUFF,
        manaCost: 50, cooldown: 10,
        buffType: BuffType.SHIELD, buffValue: 180, buffDuration: 4,
        description: 'Ghostly shield',
      },
      {
        id: 'pk_e', name: 'Spirit Storm', slot: 'E',
        type: AbilityType.AREA,
        manaCost: 90, cooldown: 30,
        damage: 140, radius: 160, duration: 2,
        buffType: BuffType.SLOW, buffValue: 0.4, buffDuration: 2.5,
        description: 'Spirit storm that damages and slows',
      },
    ],
  },
};

export const heroIds = Object.keys(heroDataMap);
